config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resource :users, only: %i[show edit update]
  get 'search' => 'rooms#search'
  resources :reservations, only: %i[edit update]
  
  delete "/reservations/:id/destroy" => "reservations#destroy"
  post '/edit_confirm/:id', to: 'reservations#edit_confirm', as: 'edit_confirm'
  resource :reservations do
    member do
      post 'confirm'
    end
  end
  post "/reservations/:id", to: 'reservations#update'
  get 'top/index'
  resource :users do
    member do
      get 'profile'
    end
  end
  resources :rooms do
    member do
      get 'photo_upload'
      get 'room_list'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-body">
    <h1><a href="/" class="footer-logo"><%= image_tag 'logo.png', size: "250x35" %></a></h1>
    <small>Copyright © Potepan Share 2023 All rights reserved</small>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar-style">
  <div class="navbar">
    <a href="/" class="left-menu">
      <%= image_tag 'logo.png', size: "250x35" %>
    </a>
    <% if user_signed_in? %>
      <div>
        <ul class="right-menu">
          <li>
            <% if current_user.avatar.attached? %>
              <%= image_tag current_user.avatar, class: 'userimage', size: "40x40" %>
            <% else %>
              <%= image_tag 'icon.png', size: "40x40" %>
            <% end %>
          </li>
          <li><%= current_user.name %></li>
          <li class="mark">∨</li>
        </ul>
      </div>
    <% else %>
      <div>
        <%= link_to "ログイン", new_user_session_path, class: 'post login-button' %>
        <%= link_to "新規登録", new_user_registration_path, class: 'post new-button' %>
      </div>
    <% end %>
    
  </div>
  <% if user_signed_in? %>
    <div class="dropdown-list">
      <ul>
        <li class="new-menu">
          <%= link_to "施設の新規登録", new_room_path %>
        </li>
        <li><%= link_to "予約済み一覧", reservations_path %></li>
        <li><%= link_to "登録済み一覧", rooms_path %></li>
        <li>
          <%= link_to "アカウント設定", users_path(current_user) %>
        </li>
        <li class="logout-menu">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </li>
      </ul>
    </div>
  <% end %>
</nav>
<%= javascript_pack_tag 'navbar' %>

app/views/shared/_search.html.erb
<div class="search-wrapper">
  <div class="keyword-search">
    <%= form_with url: search_path, method: :get, local: true do |f| %>
      <%= f.text_field :keyword, placeholder: "エリア名を入力" %>
      <%= f.hidden_field :method, value: 'area' %>
      <%= f.submit "検索" %>
    <% end %>
  </div>
  <div class="keyword-search">
    <%= form_with url: search_path, method: :get, local: true do |f| %>
      <%= f.text_field :keyword, placeholder: "キーワード名を入力" %>
      <%= f.hidden_field :method, value: 'key' %>
      <%= f.submit "検索" %>
    <% end %>
  </div>
</div>