config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resource :users, only: %i[show edit update]
  get 'search' => 'rooms#search'
  resources :reservations, only: %i[edit update]
  
  delete "/reservations/:id/destroy" => "reservations#destroy"
  post '/edit_confirm/:id', to: 'reservations#edit_confirm', as: 'edit_confirm'
  resource :reservations do
    member do
      post 'confirm'
    end
  end
  post "/reservations/:id", to: 'reservations#update'
  get 'top/index'
  resource :users do
    member do
      get 'profile'
    end
  end
  resources :rooms do
    member do
      get 'photo_upload'
      get 'room_list'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_one_attached :image
  
  validates :checkin_date, presence: true
  validates :checkout_date, presence: true
  validates :guests, presence: true
   
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_reservation, except: [:show, :new, :create, :confirm, :edit, :destroy]
  
  def show
    @reservations = current_user.reservations.order(checkin_date: :asc)
  end

  def confirm
    @user_id = current_user.id
    @reservation = Reservation.new(reservation_params)
    if @reservation.invalid?
      redirect_to room_path(@reservation.room_id), alert: '予約情報が不足しています'
    elsif @reservation.checkout_date <= @reservation.checkin_date
      redirect_to room_path(@reservation.room_id), alert: '過去と当日の日付は選択できません'
    elsif @reservation.guests.to_i <= 0
      redirect_to room_path(@reservation.room_id), alert: '人数には数字を入力してください'
    else
      count_totalprice_and_staydays
    end
  end
  
  def edit_confirm
    @reservation = Reservation.new(reservation_params)
    if @reservation.invalid?
      redirect_to edit_reservation_path, alert: '予約情報が不足しています'
    elsif @reservation.checkout_date <= @reservation.checkin_date
      redirect_to edit_reservation_path, alert: '過去と当日の日付は選択できません'
    elsif @reservation.guests.to_i <= 0
      redirect_to room_path(@reservation.room_id), alert: '人数には数字を入力してください'
    else
      count_totalprice_and_staydays
    end
  end
  
  def new
  end
  
  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      redirect_to reservations_path
      flash[:notice] = "予約が完了しました。"
    end
  end
  
  def edit
    @reservations = Reservation.find(params[:id])
  end
  
  def update
    if @reservation.update(reservation_params)
      flash[:notice] = "保存しました。"
      redirect_to reservations_path
    else
      flash[:alert] = "問題が発生しました。"
      render :edit
    end
  end
  
  def destroy
    @reservations = Reservation.find(params[:id])
    @reservations.destroy
    flash[:notice] = "予約を削除しました"
    redirect_to reservations_path
  end
  
  private
    def reservation_params
      params.require(:reservation).permit(:checkin_date, :checkout_date, :stay_days, :guests, :total_price, :room_id, :user_id)
    end
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end
    def count_totalprice_and_staydays
      start_date = Date.parse(reservation_params[:checkin_date])
      end_date = Date.parse(reservation_params[:checkout_date])
      days = (end_date - start_date).to_i
      @reservation.stay_days = days
      @reservation.total_price = @reservation.room.fee * @reservation.guests * days
    end
end
  

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/confirm.html.erb
<div class="reservation-container">
  <h1>予約内容の確認</h1>
  <div class="room-section-wrapper">
    <div class="room-section-list">
      <ul class="list-left">
        <li>チェックイン</li>
        <li>チェックアウト</li>
        <li>日数</li>
        <li>人数</li>
        <li>お支払い金額</li>
      </ul>
    </div>
    <div class="room-section-list">
      <%= form_with model:@reservation do |f| %>
        <%= f.hidden_field :room_id, value: @reservation.room_id %>
        <%= f.hidden_field :user_id, value: @reservation.user_id %>
        <%= f.hidden_field :guests, value: @reservation.guests %>
        <%= f.hidden_field :checkin_date, value: @reservation.checkin_date %>
        <%= f.hidden_field :checkout_date, value: @reservation.checkout_date %>
        <%= f.hidden_field :total_price, value: @reservation.total_price %>
      　<ul class="list-right">
      　   <li><%= @reservation.checkin_date.strftime("%Y/%m/%d")%></li>
          <li><%= @reservation.checkout_date.strftime("%Y/%m/%d")%></li>
          <li><%= @reservation.stay_days%>日</li>
          <li><%= @reservation.guests%>人</li>
          <li>￥<%= @reservation.total_price%></li>
      　</ul>
    </div>
  </div>
  <p>上記内容で正しければ「確定」ボタンを押してください。</p>
  <div>
    <%= f.submit "予約を確定", class: "button orange" %>
    <% end %>
    <%= link_to "キャンセル", :back, class: "button reservation-cancel" %>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/reservations/edit.html.erb
<div class="reservation-edit-wrapper">
  <h1>再予約する</h1>
  <div class="room-contents">
    <div class="room-image">
      <p><%= image_tag @reservations.room.image, size: "400x250"%></p>
    </div>
    
    <div class="room-details">
      <div class="room_details-contents">
         <ul>
           <li class="room-name"><%= @reservations.room.room_name %></li>
           <li class="room-address"><%= @reservations.room.address %></li>
           <li class="star">★️ ★ ★ ★ ★</li>
           <li class="room-comments"><%= @reservations.room.room_details %></li>
         </ul>
         <p class="room-fee">¥ <%= @reservations.room.fee %> ~</p>
      </div>
      <div class="new-reservation-container">
        <%= form_for @reservations, url: edit_confirm_path(@reservations), method: :post do |f| %>
        <%= f.hidden_field :room_id, value: @reservations.room_id %>
        <%= f.hidden_field :user_id, value: @reservations.user_id %>
          <div class="reservation-textforms">
            <div class="forms date" id="picker">
              <%= f.label :checkin_date, "チェックイン"%><br />
              <%= f.date_field :checkin_date, class: "reservation-form", id: "picker" %>
            </div>
            <div class="forms date"  id="datetimepicker7">
              <%= f.label :checkout_date, "チェックアウト"%><br />
              <%= f.date_field :checkout_date, class: "reservation-form", id: "picker" %>
            </div>
            <div class="forms">
              <%= f.label :guests, "人数"%><br />
              <%= f.text_field :guests, class: "reservation-form" %>
            </div>
          </div>
        <%= f.submit "再予約する", class: "button orange" %>
        <%= link_to "キャンセル", :back, class: "button reservation-cancel" %>
        <% end %>
       </div>
    </div>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/reservations/edit_confirm.html.erb
<div class="reservation-container">
  <h1>予約内容の確認</h1>
  <div class="room-section-wrapper">
    <div class="room-section-list">
      <ul class="list-left">
        <li>チェックイン</li>
        <li>チェックアウト</li>
        <li>日数</li>
        <li>人数</li>
        <li>お支払い金額</li>
      </ul>
    </div>
    <div class="room-section-list">
      <%= form_with model:@reservation ,url: {controller: 'reservations', action: 'update' } do |f| %>
        <%= f.hidden_field :room_id, value: @reservation.room_id %>
        <%= f.hidden_field :user_id, value: @reservation.user_id %>
        <%= f.hidden_field :guests, value: @reservation.guests %>
        <%= f.hidden_field :checkin_date, value: @reservation.checkin_date %>
        <%= f.hidden_field :checkout_date, value: @reservation.checkout_date %>
        <%= f.hidden_field :total_price, value: @reservation.total_price %>
      　<ul class="list-right">
      　   <li><%= @reservation.checkin_date%></li>
          <li><%= @reservation.checkout_date%></li>
          <li><%= @reservation.stay_days%></li>
          <li><%= @reservation.guests%></li>
          <li><%= @reservation.total_price%></li>
      　</ul>
    </div>
  </div>
  <p>上記内容で正しければ「確定」ボタンを押してください。</p>
  <div>
    <%= f.submit "予約を確定", class: "button orange" %>
    <% end %>
    <%= link_to "キャンセル", :back, class: "button reservation-cancel" %>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/reservations/show.html.erb
<h1 class="list-title">予約済み一覧</h1>
 
 <table class="list-table">
   <thead>
     <tr>
       <th>画像</th>
       <th>施設名</th>
       <th>紹介文</th>
       <th>合計料金</th>
       <th>チェックイン</th>
       <th>チェックアウト</th>
       <th>予約確定日時</th>
     </tr>
   </thead>
 
   <tbody>
       <% @reservations.each do |reservation| %>
       <tr>
         <td>
          <% if reservation.room.image.attached? %>
            <%= image_tag reservation.room.image, size: "100x80"%>
          <% else %>
            <%= image_tag 'default.png', size: "100x80"%>
          <% end %>
         </td>
         <td><%= link_to reservation.room.room_name, room_path(reservation.room_id) %></td>
         <td><%= reservation.room.room_details %></td>
         <td>¥<%= reservation.total_price %></td>
         <td><%= reservation.checkin_date.strftime("%Y/%m/%d") %></td>
         <td><%= reservation.checkout_date.strftime("%Y/%m/%d") %></td>
         <td><%= reservation.created_at.to_s(:datetime_jp) %></td>
         <td><%= link_to "編集", edit_reservation_path(reservation) %></td>
         <td><%= link_to "削除", "/reservations/#{reservation.id}/destroy" , method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
       </tr>
       <% end %>
     
   </tbody>
 </table>
 
 <%= render 'shared/footer' %>
 