config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resource :users, only: %i[show edit update]
  get 'search' => 'rooms#search'
  resources :reservations, only: %i[edit update]
  
  delete "/reservations/:id/destroy" => "reservations#destroy"
  post '/edit_confirm/:id', to: 'reservations#edit_confirm', as: 'edit_confirm'
  resource :reservations do
    member do
      post 'confirm'
    end
  end
  post "/reservations/:id", to: 'reservations#update'
  get 'top/index'
  resource :users do
    member do
      get 'profile'
    end
  end
  resources :rooms do
    member do
      get 'photo_upload'
      get 'room_list'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reservations ,dependent: :destroy
  has_one_attached :image
  validates :room_name, presence: true
  validates :room_details, presence: true
  validates :fee, presence: true
  validates :address, presence: true
  validates :image, content_type: { in: %w[image/jpeg image/gif image/png],
                    message: "有効なフォーマットではありません" },
                    size: { less_than: 5.megabytes, message: " 5MBを超える画像はアップロードできません" }
  
  def self.search(keyword, method)
    if method== 'area'
      where(["address like?", "%#{keyword}%"])
    elsif method == 'key'
      where(["room_name like? OR room_details like?", "%#{keyword}%", "%#{keyword}%"])
    else
      where(["room_name like? OR address like? OR room_details like?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, except: [:index, :new, :create, :search, :room_list, :destroy]
  before_action :authenticate_user!, except: [:show, :index, :search, :room_list]
  before_action :current_user_room,only: %i[index]
  def index
  end

  def new
    @room = Room.new
  end

  def create
    @room = current_user.rooms.create(room_params)
    if !@room.image.attached?
      @room.image.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'default.png')), filename: 'default-image.png', content_type: 'image/png')
    else
      @room.image.attach(params[:room][:image])
    end
    if @room.save
      flash[:notice] = "新規登録しました"
      redirect_to room_path(@room)
    else
      flash[:alert] = "入力してください"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @room.image.attach(params[:room][:image]) if @room.image.blank?
    if @room.update(room_params)
      flash[:notice] = "変更内容を保存しました。"
      redirect_to room_path(@room)
    else
      flash[:alert] = "問題が発生しました。"
      render :edit
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:notice] = "施設を削除しました"
    redirect_to rooms_path
  end

  def photo_upload
  end
  
  def search
    @rooms = Room.search(params[:keyword], params[:method])
    render "room_list"
  end
  
  def room_list
  end
  
  private
    def set_room
      @room = Room.find(params[:id])
      @reservation = Reservation.new
    end
    def room_params
      params.require(:room).permit(:room_name, :room_image, :room_details, :fee, :address, :user_id, :image)
    end
    def current_user_room
      @rooms = Room.where(user_id: current_user.id)
    end

    def default_image
      
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<div class="room-container">
  <h1>施設情報の編集</h1>
  <div class="room-section">
    <%= form_for @room do |f| %>
      <div class="form-group">
        <%= f.label :room_name, "施設名"%><span class="red">*</span>
        <%= f.text_field :room_name, class: "rooms-form" %>
      </div>
      <div class="form-group">
        <%= f.label :room_details, "施設詳細"%><span class="red">*</span>
        <%= f.text_area :room_details, class: "rooms-form" %>
      </div>
      <div class="form-group">
        <%= f.label :fee, "料金"%><span class="red">*</span>
        <%= f.text_field :fee, class: "rooms-form" %>
      </div>
      <div class="form-group">
        <%= f.label :address, "住所"%><span class="red">*</span>
        <%= f.text_field :address, class: "rooms-form" %>
      </div>
      <div class="form-group">
        <%= f.label :image, "施設画像"%>
        <label class="upload room_images">画像アップロード<%= f.file_field :image, autofocus: true %></label>
      </div>
      <div><%= f.submit "保存", class: "button orange" %></div>
      <%= link_to "キャンセル", :back, class: "reservation-cancel button" %>
    <% end %>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/rooms/index.html.erb
<h1 class="list-title">登録済み一覧</h1>
 
 <table class="list-table">
   <thead>
     <tr>
       <th>画像</th>
       <th>施設名</th>
       <th>紹介文</th>
       <th>料金</th>
       <th>作成日</th>
     </tr>
   </thead>
 
   <tbody>
     <% @rooms.each do |room| %>
       <tr>
         <td><%= image_tag room.image, size: "100x80"%></td>
         <td><%= link_to room.room_name, room_path(room) %></td>
         <td><%= room.room_details %></td>
         <td>¥<%= room.fee %>~</td>
         <td><%= room.created_at.to_s(:date_jp) %></td>
         <td><%= link_to "編集", edit_room_path(room) %></td>
         <td><%= link_to "削除", room, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
       </tr>
     <% end %>
   </tbody>
 </table>
 
 <%= render 'shared/footer' %>
 

app/views/rooms/new.html.erb
<div class="room-container">
  <h1>新規登録</h1>
  <div class="room-section">
    <%= form_for @room do |f| %>
      <div class="form-group">
        <%= f.label :room_name, "施設名"%><span class="red">*</span>
        <%= f.text_field :room_name, placeholder: "ルーム名を入力", class: "rooms-form" %>
      </div>
      <div class="form-group">
        <%= f.label :room_details, "施設詳細"%><span class="red">*</span>
        <%= f.text_area :room_details, placeholder: "施設詳細を入力", class: "rooms-form" %>
      </div>
      <div class="form-group">
        <%= f.label :fee, "料金"%><span class="red">*</span>
        <%= f.text_field :fee, placeholder: "一日あたりの料金を入力", class: "rooms-form" %>
      </div>
      <div class="form-group">
        <%= f.label :address, "住所"%><span class="red">*</span>
        <%= f.text_field :address, placeholder: "住所を入力", class: "rooms-form" %>
      </div>
      <div class="form-group">
        <%= f.label :image, "施設画像"%>
        <label class="upload room_images">画像アップロード<%= f.file_field :image, autofocus: true %></label>
      </div>
      <div><%= f.submit "保存", class: "button orange" %></div>
      <%= link_to "キャンセル", :back, class: "button reservation-cancel" %>
    <% end %>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/rooms/photo_upload.html.erb
<h1>Rooms#photo_upload</h1>
<p>Find me in app/views/rooms/photo_upload.html.erb</p>

app/views/rooms/room_list.html.erb
<%= render 'shared/search' %>
<p class="roomlist-count"><%= @rooms.count %>件が見つかりました。</p>
 
<div class="roomlist-container">
  <div class="roomlist-contents">
    <% @rooms.each do |room| %>
      <div class="roomlist-wrapper">
        <div class="roomlist-image">
        <% if room.image.attached? %>
          <%= image_tag room.image, class: "roomlist-size"%>
        <% else %>
          <%= image_tag 'default.png', class: "roomlist-size"%>
        <% end %>
        </div>
        <div class="roomlist-details-wrapper">
          <div class="roomlist-name">
          <%= room.room_name %>
          </div>
          <div class="roomlist-address">
            <%= room.address %>
          </div>
          <div class="star">
            ★ ★ ★ ★ ★ 
          </div>
          <div class="roomlist-details">
            <%= room.room_details %>
          </div>
          <div class="roomlist-fee">
            ¥<%= room.fee %>~
          </div>
          <div>
            <%= link_to "詳細はこちら", room_path(room), class: "roomlist-button"%>
          </div>
        </div>
        
      </div>
      
    <% end %>
  </div>
</div>

 <%= render 'shared/footer' %>
 

app/views/rooms/show.html.erb
<%= render 'shared/search' %>
<div class="room_container">
  <div class="room-details-header">
    <%= link_to "←戻る", :back %>
    <% if user_signed_in? %>
      <% if @room.user_id == current_user.id %>
        <%= link_to "編集", edit_room_path, class: "room-edit" %>
      <% end %>
    <% end %>
  </div>
  <div class="room-contents">
    <div class="room-image">
      <p>
        <% if @room.image.attached? %>
          <%= image_tag @room.image, size: "400x250"%>
        <% else %>
          <%= image_tag 'default.png', size: "400x250" %>
        <% end %>
      </p>
    </div>
    
    <div class="room-details">
      <div class="room_details-contents">
        <ul>
          <li class="room-name"><%= @room.room_name %></li>
          <li class="room-address"><%= @room.address %></li>
          <li class="star">★️ ★ ★ ★ ★</li>
          <li class="room-comments"><%= @room.room_details %></li>
        </ul>
        <p class="room-fee">¥ <%= @room.fee %> ~</p>
      </div>
      <% if user_signed_in? %>
        <div class="new-reservation-container">
          <%= form_for @reservation, url: confirm_reservations_path(@reservation) do |f| %>
          <%= f.hidden_field :room_id, value: @room.id %>
          <%= f.hidden_field :user_id, value: current_user.id %>
            <div class="reservation-textforms">
              <div class="forms date" id="datetimepicker6">
                <%= f.label :checkin_date, "チェックイン"%><br />
                <%= f.date_field :checkin_date, min: Time.zone.now, class: "reservation-form datepicker", value: "%Y/%M/%d" %>
              </div>
              <div class="forms date"  id="datetimepicker7">
                <%= f.label :checkout_date, "チェックアウト"%><br />
                <%= f.date_field :checkout_date, class: "reservation-form datepicker" %>
              </div>
              <div class="forms">
                <%= f.label :guests, "人数"%><br />
                <%= f.text_field :guests, class: "reservation-form" %>
              </div>
            </div>
            <%= f.submit "予約する", class: "button orange reservation-button" %>
          <% end %>
        </div>
      <% else %>
        <div class="new-reservation-container">
          <%= form_for @reservation, url: new_user_session_path do |f| %>
            <div class="reservation-textforms">
              <div class="forms date" id="datetimepicker6">
                <%= f.label :checkin_date, "チェックイン"%><br />
                <%= f.date_field :checkin_date, class: "reservation-form datepicker" %>
              </div>
              <div class="forms date"  id="datetimepicker7">
                <%= f.label :checkout_date, "チェックアウト"%><br />
                <%= f.date_field :checkout_date, class: "reservation-form datepicker" %>
              </div>
              <div class="forms">
                <%= f.label :guests, "人数"%><br />
                <%= f.text_field :guests, class: "reservation-form" %>
              </div>
            </div>
            <%= f.submit "ログイン", class: "button orange reservation-button" %>
          <% end %>
        </div>
      <% end %>
      
      
    </div>
  </div>
</div>

<%= javascript_pack_tag 'datetime' %>
<%= render 'shared/footer' %>